name: Build
on:
  push:
    branches:
      - master

jobs:
  build_provider:
    name: Build Provider
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: '^1.14.4'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build provider
        run: go build -o terraform-provider-gatsby